const desktopStripes = `
linear-gradient( to right,
  var(--dark) 30px,
  var(--light) 30px,
  var(--light) 31px,
  var(--dark) 31px,
  var(--dark) calc(31px + var(--columnWidth)),
  var(--light) calc(31px + var(--columnWidth)),
  var(--light) calc(32px + var(--columnWidth)),
  var(--dark) calc(32px + var(--columnWidth)),
  var(--dark) calc(62px + var(--columnWidth)),
  var(--light) calc(62px + var(--columnWidth)),
  var(--light) calc(63px + var(--columnWidth)),
  var(--dark) calc(63px + var(--columnWidth)),
  var(--dark) calc(63px + calc(var(--columnWidth) * 2)),
  var(--light) calc(63px + calc(var(--columnWidth) * 2)),
  var(--light) calc(64px + calc(var(--columnWidth) * 2)),
  var(--dark) calc(64px + calc(var(--columnWidth) * 2)),
  var(--dark) calc(94px + calc(var(--columnWidth) * 2)),
  var(--light) calc(94px + calc(var(--columnWidth) * 2)),
  var(--light) calc(95px + calc(var(--columnWidth) * 2)),
  var(--dark) calc(95px + calc(var(--columnWidth) * 2)),
  var(--dark) calc(95px + calc(var(--columnWidth) * 3)),
  var(--light) calc(95px + calc(var(--columnWidth) * 3)),
  var(--light) calc(96px + calc(var(--columnWidth) * 3)),
  var(--dark) calc(96px + calc(var(--columnWidth) * 3)),
  var(--dark) calc(126px + calc(var(--columnWidth) * 3)),
  var(--light) calc(126px + calc(var(--columnWidth) * 3)),
  var(--light) calc(127px + calc(var(--columnWidth) * 3)),
  var(--dark) calc(127px + calc(var(--columnWidth) * 3)),
  var(--dark) calc(127px + calc(var(--columnWidth) * 4)),
  var(--light) calc(127px + calc(var(--columnWidth) * 4)),
  var(--light) calc(128px + calc(var(--columnWidth) * 4)),
  var(--dark) calc(128px + calc(var(--columnWidth) * 4)),
  var(--dark) calc(158px + calc(var(--columnWidth) * 4)),
  var(--light) calc(158px + calc(var(--columnWidth) * 4)),
  var(--light) calc(159px + calc(var(--columnWidth) * 4)),
  var(--dark) calc(159px + calc(var(--columnWidth) * 4)),
  var(--dark) calc(159px + calc(var(--columnWidth) * 5)),
  var(--light) calc(159px + calc(var(--columnWidth) * 5)),
  var(--light) calc(160px + calc(var(--columnWidth) * 5)),
  var(--dark) calc(160px + calc(var(--columnWidth) * 5)),
  var(--dark) calc(190px + calc(var(--columnWidth) * 5)),
  var(--light) calc(190px + calc(var(--columnWidth) * 5)),
  var(--light) calc(191px + calc(var(--columnWidth) * 5)),
  var(--dark) calc(191px + calc(var(--columnWidth) * 5)),
  var(--dark) calc(191px + calc(var(--columnWidth) * 6)),
  var(--light) calc(191px + calc(var(--columnWidth) * 6)),
  var(--light) calc(192px + calc(var(--columnWidth) * 6)),
  var(--dark) calc(192px + calc(var(--columnWidth) * 6)),
  var(--dark) calc(222px + calc(var(--columnWidth) * 6)),
  var(--light) calc(222px + calc(var(--columnWidth) * 6)),
  var(--light) calc(223px + calc(var(--columnWidth) * 6)),
  var(--dark) calc(223px + calc(var(--columnWidth) * 6)),
  var(--dark) calc(223px + calc(var(--columnWidth) * 7)),
  var(--light) calc(223px + calc(var(--columnWidth) * 7)),
  var(--light) calc(224px + calc(var(--columnWidth) * 7)),
  var(--dark) calc(224px + calc(var(--columnWidth) * 7)),
  var(--dark) calc(254px + calc(var(--columnWidth) * 7)),
  var(--light) calc(254px + calc(var(--columnWidth) * 7)),
  var(--light) calc(255px + calc(var(--columnWidth) * 7)),
  var(--dark) calc(255px + calc(var(--columnWidth) * 7)),
  var(--dark) calc(255px + calc(var(--columnWidth) * 8)),
  var(--light) calc(255px + calc(var(--columnWidth) * 8)),
  var(--light) calc(256px + calc(var(--columnWidth) * 8)),
  var(--dark) calc(256px + calc(var(--columnWidth) * 8)),
  var(--dark) calc(286px + calc(var(--columnWidth) * 8)),
  var(--light) calc(286px + calc(var(--columnWidth) * 8)),
  var(--light) calc(287px + calc(var(--columnWidth) * 8)),
  var(--dark) calc(287px + calc(var(--columnWidth) * 8)),
  var(--dark) calc(287px + calc(var(--columnWidth) * 9)),
  var(--light) calc(287px + calc(var(--columnWidth) * 9)),
  var(--light) calc(288px + calc(var(--columnWidth) * 9)),
  var(--dark) calc(288px + calc(var(--columnWidth) * 9)),
  var(--dark) calc(318px + calc(var(--columnWidth) * 9)),
  var(--light) calc(318px + calc(var(--columnWidth) * 9)),
  var(--light) calc(319px + calc(var(--columnWidth) * 9)),
  var(--dark) calc(319px + calc(var(--columnWidth) * 9)),
  var(--dark) calc(319px + calc(var(--columnWidth) * 10)),
  var(--light) calc(319px + calc(var(--columnWidth) * 10)),
  var(--light) calc(320px + calc(var(--columnWidth) * 10)),
  var(--dark) calc(320px + calc(var(--columnWidth) * 10)),
  var(--dark) calc(350px + calc(var(--columnWidth) * 10)),
  var(--light) calc(350px + calc(var(--columnWidth) * 10)),
  var(--light) calc(351px + calc(var(--columnWidth) * 10)),
  var(--dark) calc(351px + calc(var(--columnWidth) * 10)),
  var(--dark) calc(351px + calc(var(--columnWidth) * 11)),
  var(--light) calc(351px + calc(var(--columnWidth) * 11)),
  var(--light) calc(352px + calc(var(--columnWidth) * 11)),
  var(--dark) calc(352px + calc(var(--columnWidth) * 11)),
  var(--dark) calc(382px + calc(var(--columnWidth) * 11)),
  var(--light) calc(382px + calc(var(--columnWidth) * 11)),
  var(--light) calc(383px + calc(var(--columnWidth) * 11)),
  var(--dark) calc(383px + calc(var(--columnWidth) * 11)),
  var(--dark) calc(383px + calc(var(--columnWidth) * 12)),
  var(--light) calc(383px + calc(var(--columnWidth) * 12)),
  var(--light) calc(384px + calc(var(--columnWidth) * 12)),
  var(--dark) calc(384px + calc(var(--columnWidth) * 12))
)
`

export default desktopStripes
